### ISSUE TITLE
[Bug] Mass Edit and Drag Ruler conflict in PF2e

### ISSUE THREAD

**Issue by ksignorini** [Aedif/multi-token-edit#32]
I get the following when trying to drag a token into the Presets window:

<img width="553" alt="image" src="https://github.com/Aedif/multi-token-edit/assets/6867660/67840ba7-71cb-4374-b3f5-312350df1d0f">

**Comment by pandanielxd** [comment]
While not the same module, I wanted to add that a similar module Elevation Ruler gets the same warning
![DQEWrXJ](https://github.com/user-attachments/assets/eb1523d6-0ce1-4fe6-b12d-fb97da07530c)

**Comment by Armandeus66** [comment]
I get the same kind of error.

```
libWrapper-notifications.js:90 [W] libWrapper: module PF2e Token Drag Ruler and module Baileywiki Mass Edit modify the same FoundryVTT functionality and are more likely to conflict.
Module pf2e-ruler did not chain the wrapper for 'Token.prototype._onDragLeftDrop'.
🎁console_ui @ libWrapper-notifications.js:90Understand this warning
foundry.js:72076 libWrapper: module PF2e Token Drag Ruler and module Baileywiki Mass Edit modify the same FoundryVTT functionality and are more likely to conflict. (See JS Console)

Foundry VTT | Rendering ImageHoverHUD
3foundry-esm.js:4621 Error: You are accessing TokenDocumentPF2e#actorData which has been migrated to TokenDocumentPF2e#delta
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
    at logCompatibilityWarning (foundry-esm.js:4609:19)
    at TokenDocumentPF2e._logDataFieldMigration (foundry-esm.js:12119:14)
    at Object.get (foundry-esm.js:12080:21)
    at Object.fn (combat.js:246:17)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at foundry-esm.js:56584:17
    at foundry-esm.js:56590:43
    at Array.map (<anonymous>)
    at #handleUpdateDocuments (foundry-esm.js:56590:33)
    at async TokenDocumentPF2e.updateDocuments (foundry-esm.js:11473:23)
    at async TokenDocumentPF2e.update (foundry-esm.js:11584:23)
    at async DragRuler._animateSegment (dragRuler.js:567:9)
    at async DragRuler._animateMovement (dragRuler.js:546:13)
    at async DragRuler.moveToken (dragRuler.js:487:13)
```
